---
title: Javascript - 자바스크립트 동작 원리
date: '2023-02-08'
tags: ['Javascript']
draft: false
---

자바스크립트가 동작하는 기본 원리를 알기 위해서는 `동기`, `비동기`의 개념을 먼저 알아야 한다.

## 동기(synchronous: 동시에 일어나는)

동기는 요청과 그 결과가 동시에 일어나는 것을 의미한다. 프린터를 예로 들면, 프린터는 요청이 들어온 순서대로 프린팅을 해주고 이전 요청작업이 완료되지 않으면 다음 작업을 실행하지 않는다. 순서대로 진행되는 장점이 있지만 여러가지를 동시에 처리 할 수 없다는 단점이 있다.

## 비동기(asynchronous: 동시에 일어나지 않는)

비동기는 이전의 요청에 대한 응답이 끝날때까지 기다리는 것이 아니라, 바로 다음 동작을 실행하는 것을 의미한다. 이 경우는 보통 멀티 스레드 환경에서 동작하는데, 멀티 스레드는 여러개의 스레드가 동시에 동작할 수 있다. 스레드가 여러개가 있기 때문에, 하나의 요청이 끝날때까지 기다리지 않고 다른 스레드로 넘어가서 요청을 수행할 수 있는 것이다.

`Javscript`는 인터프리터 언어이기 때문에 순차적으로 코드가 실행된다. 따라서 동기식 언어이다.

> Thread란 프로세스가 할당받은 자원을 이용하는 실행의 단위를 말한다.

## Call stack

자바스크립트는 함수를 호출하면 실행 컨텍스트가 생성되고, 이 실행 컨텍스트는 Call stack에 하나씩 쌓인다. 이 Call stack은 하나밖에 없기 때문에 자바스크립트가 single thread 언어 인 것이다. stack은 Last In First Out 형태로 동작하는 자료구조로, 맨위에 있는 것부터 실행이 된다.

아래 코드를 예시로 들어보자

```Javascript
console.log('a')
console.log('b')
console.log('c')
```

이 코드는 순서대로 콘솔에 a,b,c를 보여줄 것이다. stack에는 `console.log('c')`부터 순차적으로 쌓이게 되기 때문에, 마지막에 stack에 들어온 `console.log('a')`가 가장 먼저 실행된다. 그런데 모든 코드가 다 이 call stack에 쌓이는 것은 아니다.

## CallBack Que

특별한 코드를 만나면 대기열에 코드를 넣고, stack이 완전히 비어지면 그때 실행하게 된다. 이 대기열을 `CallBack Que` 라고 한다. 큐는 스택과 다르게 `First In First Out`형태로 동작한다. 따라서 먼저 들어온 코드가 가장 먼저 실행된다.

이 `CallBack Que`에 들어오는 특별한 코드는 `ajax`, `event listener`, `setTimeout`이 있다. 이 코드들의 특징은 처리하기까지 시간이 오래걸린다는 것이다. 만약 이런 코드들까지 다 call stack에 쌓여있다면 자바스크립트는 처리 속도가 매우 느려질 것이다. 왜냐하면 자바스크립트는 동기적으로 동작하기 때문에, 한가지 동작을 완전히 처리하기 전까지 다음 동작들은 모두 block이 되기 때문이다.

하지만 자바스크립트는 non-block 언어이다. 그 이유는 자바스크립트가 비동기적으로 동작 할 수도 있기 때문이다. 지금까지 계속 자바스크립트가 동기적으로 동작한다고 해놓고 비동기라니? 라고 생각이 들것이다.

분명히 자바스크립트는 동기적 언어가 맞다. 하지만 WebAPI 덕분에 비동기적으로 동작 할 수 있다.

`ajax`, `event listener`, `setTimeout`의 두번째 특징은 WebAPI라는 것이다. WebAPI는 웹 브라우저를 위한 인터페이스로 웹페이지 개발을 좀 더 편리하게 도와주는 객체들이다. 따라서 `ajax`, `event listener`, `setTimeout`이 실행되면 자바스크립트 엔진이 아닌 브라우저에서 처리하게 된다.

가장 일반적으로 예를 많이 드는 setTimout으로 동작순서를 보자.

```Javascript

function test() {
	console.log('a')
}

function test2(){
	console.log('b')
}

test()
setTimeout(()=> console.log('c'), 2000)
test2()
```

위 코드를 실행하면, test와 test2 함수는 call stack에 들어갈 것이고 setTimeout 함수는 WebAPI로 넘어가서 타이머를 실행시킨다. 타이머가 완료되면 `console.log('c')`를 실행시키는 콜백함수가 CallBack que에 들어갈 것이다. 그리고 test와 test2가 모두 실행되고 call stack이 비면 CallBack que에 대기하고 있던 함수가 call stack으로 들어가 실행된다.

> ✅ CallBack que의 함수는 call stack이 텅텅 비어야 call stack에 들어갈 수 있다

## 자바스크립트는 싱글스레드지만 멀티스레드처럼 동작한다?

분명 자바스크립트는 동기적으로, 싱글스레드로 동작한다. 하지만 setTimeout의 예시를 보면 비동기적으로 동작하고 있는 것을 볼 수 있다. 즉 자바스크립트 자체는 싱글스레드지만 setTimeout과 같은 WebAPI는 브라우저에서 따로 처리를 해주기 때문에, 멀티스레드로 동작하는 것처럼 보이는 것이다.

## 자바스크립트 코드 원하는 순서로 동작시키기 - 콜백지옥

setTimeout과 같이 비동기로 동작하는 함수가 있으면 정확히 언제 실행이 끝나는지 알 수가 없다. 예를 들면, 위에 예시로 들었던 코드에서 setTimeout 함수가 실행된 이후에 test2 함수를 실행시키고 싶다고 가정해보자. 정확히 setTimeout 함수가 언제 끝나는지 알 수 없기 때문에, test2함수를 순차적으로 실행시키고자 한다면 콜백함수로 만들어주어야 한다.

```javascript
function test() {
  console.log('a')
}

function test2() {
  console.log('b')
}

function timer(fn) {
  setTimeout(() => {
    console.log('c')
    fn()
  }, 2000)
}

test()
timer(test2)
```

위 코드는 매우 간단한 경우다. 만약에 더 많은 함수를 순서대로 동작시켜야 한다면 아마 아래와 같은 형태가 될 것이다.

```javascript
function test() {
  console.log('a')
}

function test2(fn) {
  console.log('b')
  fn()
}

function timer(fn) {
  setTimeout(() => {
    console.log('c')
    fn()
  }, 2000)
}

timer(() => test2(test))
```

결국에는 이런형태까지..

```javascript
timer(() => test2(()=>test(()=> testchild()))
```

이렇게 되면 `콜백 지옥`에 빠지게 되는 것이다.

## 콜백 지옥 해결하기 - Promise

콜백지옥은 Promise로 해결할 수가 있다. Promise는 문자그대로 약속하는 것이다. Promise는 매개변수로 `executor(실행함수)`를 받는데 이 실행함수에서는 `resolve`, `reject`두가지 파라미터를 받는다. 이 `executor`는 보통 비동기 작업을 시작한 후 모든 작업을 끝내면 `resolve`를 호출해서 약속된 함수를 실행시켜주고, 만약 오류가 생겼을 경우에는 `reject`를 호출해서 약속 이행을 거부한다.

예시를 보는 것이 이해가 빠르니 예시코드를 보자.

```javascript
const promiseEx = new Promise((resolve, reject) => {
  setTimeout(() => resolve('timer'), 2000)
}) // new 생성자로 Promise 객체를 생성해준다.

promiseEx
  .then((value) => console.log(value))
  .then(() => console.log('a'))
  .then(() => console.log('b'))
```

위 코드를 해석해보면,

1. promiseEx의 실행함수(executor)가 실행되면서 setTimeout 함수를 실행시킨다.
2. promiseEx의 첫번째 then의 콜백함수는 Promise가 비동기 작업을 성공적으로 완료한 결과를 보여준다.
3. 따라서 setTimeout 함수가 2초간의 timer 실행을 마치고,
4. setTimeout 콜백함수인 `()=> resolve('timer')`가 실행된 후
5. resolve로 보내준 'timer'가 첫번째 then의 결과값으로 노출된다.
6. 그리고 첫번째 then이 성공적으로 끝나면 그 다음 then의 콜백을 실행시켜준다.

이 코드는 콜백지옥 코드와 비교했을때 가독성의 차이가 굉장히 많이 난다.

## catch로 error 처리하기

Promise를 사용했을때 좋은 점은 특정 조건에서 error 처리를 할 수 있다는 것이다.
then이 Promise가 성공했을때라면 catch는 에러 처리를 할때 사용할 수 있다.

```javascript
const promiseEx = async (ms) =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve('timer'), ms)
    if (typeof ms !== 'number') {
      reject('숫자가 아닙니다')
    }
  })

promiseEx(1000)
  .then((value) => console.log(value))
  .then(() => console.log('a'))
  .then(() => console.log('b'))

promiseEx('d')
  .then((value) => console.log(value))
  .then(() => console.log('a'))
  .then(() => console.log('b'))
  .catch((err) => console.log(err))
```

위 코드를 실행해보면 두번째로 실행한 Promise는 인자값을 숫자로 주지 않았기 때문에 에러가 발생하게 된다.

## finally로 무조건 실행해주는 코드 만들어주기

finally를 사용하면 성공했던 실패했던 무조건 실행해주는 코드를 넣어줄 수 있다.
아래 코드를 실행하면 타입 에러로 catch가 실행되는데, finally도 함께 실행된다.

```javascript
promiseEx('d')
  .then((value) => console.log(value))
  .then(() => console.log('a'))
  .then(() => console.log('b'))
  .catch((err) => console.log(err))
  .finally(() => console.log('promise 끝'))
```

## async와 await

Promise와 then, 그리고 catch의 조화로 비동기 작업시의 콜백지옥을 무사히 벗어났지만 또다른 문제가 있다. then 콜백 내부에서 또 다른 Promise를 실행하거나, then으로 처리해야할 단계가 너무 많거나 하면 then 지옥에 빠지게 된다.

### then 지옥

```javascript
const textPromise = new Promise((resolve) => {
  fetch('https://codingapple1.github.io/hello.txt', {
    method: 'GET',
  }).then((res) => {
    resolve(res.text())
  })
})
const text2Promise = new Promise((resolve) => {
  fetch('https://codingapple1.github.io/hello2.txt', {
    method: 'GET',
  }).then((res) => {
    resolve(res.text())
  })
})
textPromise
  .then((res) => {
    console.log(res)
  })
  .then(() => {
    text2Promise.then((res) => {
      console.log(res)
    })
  })
```

이럴때 async, await을 사용하면 더 깔끔하게 작성이 가능해진다. async로 함수를 감싸면 해당 함수sms Promise를 반환한다. 그리고 내부에 await을 사용하면 Promise의 then과 같은 기능을 하게 된다.
그럼 위 예시코드를 async, await으로 변환해보자

```javascript
const textPromise = async () => {
  const text = await (await fetch('https://codingapple1.github.io/hello.txt')).text()
  return console.log(text)
}
const text2Promise = async () => {
  const text = await (await fetch('https://codingapple1.github.io/hello2.txt')).text()
  return console.log(text)
}
;(async () => {
  await textPromise()
  await text2Promise()
})()
```

이렇게 또 한번 더 코드가 깔끔해진 것을 볼 수 있다.

## async, await에서 error 처리하기

async와 await에서 error 처리를 하려면 try, catch를 사용하면 된다.

```javascript
const textPromise = async () => {
  const text = await (await fetch('https://codingapple1.github.io/hello.txt')).text()
  return console.log(text)
}
const text2Promise = async () => {
  const text = await (await fetch('https://codingapple1.github.io/hello2.txt')).text()
  return console.log(text)
}
const getNum = async (num) => {
  const nums = (await num) + 2
  if (typeof num !== 'number') {
    throw Error('숫자가 아닙니다.')
  }
  return console.log(num)
}
;(async () => {
  try {
    await textPromise()
    await text2Promise()
    await getNum('2')
    await getNum(2)
  } catch (error) {
    console.log(error)
  }
})()
```

위 코드에서 getNum함수의 인자값의 타입이 number가 아니면 에러를 발생시키도록 했다. 그리고 try, catch를 통해서 error가 생기면 콘솔에 에러 메세지를 노출시키도록 했다.

그럼 위 코드의 결과물은 아래와 같다.

```bash
'안녕하세요 반갑습니다요.'
'두번째 인삿말입니다'

 Error: 숫자가 아닙니다.
    at getNum (index.html:84:15)
    at async index.html:92:9
```

앞서 말했듯 promise는 error가 발생하면 그 다음 실행문을 실행하지 않는다. 위 코드의 결과물에서도
`getNum('2')`에서 error가 발생했고 이후의 실행문인 `await getNum(2)`은 실행되지 않은 것을 볼 수 있다.

즉 형태는 다르지만 promise와 완전 동일한 기능을 하고 있다는 것이다.

이렇게 자바스크립트 동작원리, 비동기와 동기, 비동기 코드 처리 방법에 대해 잘 이해하고 있으면 효율적이고 예쁜 코드를 작성할 수 있다. 특히 fetch로 api 데이터를 받아와야 하는 프론트 작업을 제대로 하기 위해서는 깊게 이해하는 것이 필요하다.
